package project1;

public class drawing_object {
	public static void underscore(int x,int b){ /* x is a variable used for to determine number of underscore
        b is a variable used for to determine number of spaces after underscore */
		for(int a=1;a<=x;a++){  /* b is a variable used for to determine number of dollar
c is a variable used for to determine number of spaces after dollar */
			System.out.print("_");
		}
		for(int d=1;d<=b;d++){
			System.out.print(" ");
		}
	}
	public static void dollar(int b,int c){
		for(int a=1;a<=b;a++){
			System.out.print("$");
		}
		for(int e=1;e<=c;e++){
			System.out.print(" ");
		}
	}
	public static void main(String[] args){
		underscore(12,0);
		dollar(13,0);
		System.out.println();
		underscore(8,0);
		dollar(7,1);			
		underscore(9,0);
		dollar(3,0);
		System.out.println();
		underscore(5,0);
		dollar(9,1);				
		underscore(11,1);				
		dollar(4,0);
		System.out.println();
		underscore(4,0);
		dollar(2,0);
		underscore(1,0);
		dollar(3,0);
		underscore(4,0);
		dollar(2,1);			
		underscore(8,1);				
		dollar(1,0);
		underscore(3,0);
		dollar(2,0);
		System.out.println();
		underscore(3,0);
		dollar(1,0);
		underscore(3,0);
		dollar(1,0);
		underscore(8,0);
		dollar(1,1);			
		underscore(6,1);				
		dollar(1,0);
		underscore(6,0);
		dollar(2,0);
		System.out.println();
		underscore(2,0);
		dollar(1,0);
		underscore(3,0);
		dollar(1,1);			  
		underscore(9,1);			   
		dollar(8,0);
		underscore(7,0);
		dollar(2,0);
		System.out.println();
		underscore(1,0);
		dollar(1,0);
		underscore(3,0);
		dollar(2,1);			    
		underscore(8,1);			    
		dollar(9,0);
		underscore(8,0);
		dollar(2,0);
		System.out.println();
		dollar(2,0);
		underscore(3,0);
		dollar(1,1);				
		underscore(9,1);				
		dollar(10,0);
		underscore(8,0);
		dollar(1,0);
		System.out.println();
		dollar(1,0);
		underscore(3,0);
		dollar(2,1);			
		underscore(7,0);
		dollar(14,0);
		underscore(7,0);
		dollar(1,0);
		System.out.println();
		dollar(1,0);
		underscore(2,0);
		dollar(5,1);		     
		underscore(2,1);	       
		dollar(3,0);
		underscore(3,0);
		dollar(7,0);
		underscore(2,1);		       
		dollar(4,0);
		underscore(3,0);
		dollar(2,0);
		System.out.println();
		dollar(11,1);				
		underscore(7,1);				
		dollar(3,0);
		underscore(8,0);
		dollar(5,0);
		System.out.println();
		dollar(1,0);
		underscore(1,0);
		dollar(7,1);				
		underscore(10,1);				
		dollar(1,0);
		underscore(10,0);
		dollar(4,0);
		System.out.println();
		dollar(1,0);
		underscore(1,0);
		dollar(7,1);			
		underscore(10,1);				
		dollar(1,0);
		underscore(10,0);
		dollar(4,0);
		System.out.println();
		underscore(1,0);
		dollar(1,0);
		underscore(1,0);
		dollar(6,1);				
		underscore(9,1);			
		dollar(2,0);
		underscore(10,1);			
		dollar(3,0);
		System.out.println();
		underscore(2,0);
		dollar(1,0);
		underscore(1,0);
		dollar(2,0);
		underscore(2,0);
		dollar(2,1);			
		underscore(8,1);			
		dollar(1,0);
		underscore(9,0);
		dollar(2,0);
		underscore(1,0);
		dollar(2,0);
		System.out.println();
		underscore(3,0);
		dollar(2,0);
		underscore(5,0);
		dollar(3,1);				
		underscore(3,1);			
		dollar(5,0);
		underscore(4,0);
		dollar(3,0);
		underscore(3,0);
		dollar(1,0);
		System.out.println();
		underscore(4,0);
		dollar(2,1);				
		underscore(5,1);				
		dollar(15,0);
		underscore(3,0);
		dollar(2,0);
		System.out.println();
		underscore(5,0);
		dollar(3,1);				
		underscore(5,1);				
		dollar(10,0);
		underscore(4,0);
		dollar(2,0);
		System.out.println();
		underscore(7,0);
		dollar(4,1);				
		underscore(2,1);			
		dollar(9,0);
		underscore(2,0);
		dollar(3,0);
		System.out.println();
		underscore(10,0);
		dollar(5,1);			
		underscore(5,1);			
		dollar(4,0);
		System.out.println();
		underscore(14,0);
		dollar(7,0);											
	}

}
